Repository aws-cloudformation/cloudformation-cli, pull requests merged in 2020-06, with the labels that each got.

#453 Remove Callback Context assert for handler success and failure
  src/rpdk/core/contract/resource_client.py
  tests/contract/test_resource_client.py
Labels: contract tests

#454 added generic type for multiple type support
  src/rpdk/core/jsonutils/resolver.py
  src/rpdk/core/project.py
  tests/data/schema/valid/valid_pattern_properties.json
  tests/jsonutils/test_resolver.py
Labels: bug, codegen

#457 Initial docs source
  docs/README.md
  docs/RESOURCE_MODELLING.md
Labels: documentation, resource-provider-guidance

#469 Use relative links
  docs/README.md
Labels: documentation

#471 Fix relative link
  docs/README.md
Labels: documentation
