Repository aws-cloudformation/cloudformation-cli, pull requests merged in 2022-11, with the labels that each got.

#924 fix(cli): `cfn test` broken on Windows - NamedTemporaryFile issue
  src/rpdk/core/test.py
  tests/test_test.py
Labels: bug, cli experience, p0

#740 `generate_docs()` for conditionalCreateOnlyProperties
  src/rpdk/core/project.py
  src/rpdk/core/templates/docs-readme.md
  src/rpdk/core/templates/docs-subproperty.md
  tests/data/schema/valid/valid_type_complex.json
Labels: documentation

#943 fix(jinja2): upgrade jinja2 and markupsafe
  .gitattributes
  setup.py
  src/rpdk/core/contract/hook_client.py
  src/rpdk/core/templates/docs-readme.md
  src/rpdk/core/templates/docs-subproperty.md
  src/rpdk/core/templates/hook-docs-readme.md
Labels: enhancement, code quality, cli experience
